### ISSUE TITLE
UTC serialisation

### ISSUE THREAD

**Issue by cmaish** [janpieterz/Warden.Integrations.Seq#1]
Hi there!

I just started using the library, but have noticed that the events that get logged into Seq don't seem to be preserving the DateTime kind.  It looks like this is due to SeqIntegrationConfiguration.DefaultJsonSerializerSettings.DateFormatString being configured without timezone information.

Our current workaround is to call something roughly equivalent to:
SeqIntegrationConfiguration.DefaultJsonSerializerSettings.DateFormatString =
                "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";
before startup.

This has an impact of adjusting all dates, but has worked for us so far.  Just figured that I should let you / others who might come across the project know.

**Comment by janpieterz** [comment]
Thanks! Any way you could create a pull request for this? I'd be happy to merge it into the official package.
